package com.ecommerce.engine.enums;

public enum EventType {
    ORDER_CREATED, PAYMENT_SUCCESS, PAYMENT_FAILED, INVENTORY_UPDATED,
    ORDER_CANCELLED, ORDER_SHIPPED, ORDER_DELIVERED,
    STOCK_RESERVED, STOCK_RELEASED, RETURN_INITIATED, FRAUD_DETECTED
}
